### ISSUE TITLE
[Suggestion] Todo List

### ISSUE THREAD

**Issue by jani270** [nea89o/LocalTransactionLedger#7]
- [ ] Trading
- [x] Forge
- [x] Copper Shop
- [x] Corpse open
- [x] High Class / Archfined Dice
- [ ] Minion Items (Refuel)
- [x] Inferno Minion Eyedrops
 - `You applied the eyedrops on the minion and ran out!`
- [ ] Fann Pet Leveling
- [ ] Slayer Start Cost
- [ ] Slayer Mob Drops
- [x] Chocolate Shop
- [ ] Exp Bottle throwing
- [ ] Attribute combine cost
- [x] Eye placement
- [ ] Scrap
- [ ] Reforge cost
- [ ] Salvage
- [ ] Armor Star
- [ ] Anvil Combine
- [ ] Hex
- [ ] Diana Dug Out
 - `Wow! You dug out 10,000 coins!` `Wow! You dug out 500,000 coins!` `§r§6§lRARE DROP! §r§eYou dug out a §r§6Crown of Greed§r§e!§r`
- [ ] Gift Coins/Items
- [x] Draconic Sacrifice
- [x] God Potion drinking
- [x] God Potion Mixins drinking
- [x] Caducous Feeder
- [x] Enrichment Swapper
